on: [push]

env:
  UPSTREAM_PATH: https://github.com/openpmix/openpmix/releases/download/v4.2.3/pmix-4.2.3-1.src.rpm
  
jobs:
  first-job:
    name: produce rpms
    runs-on: ubuntu-22.04
    container: docker://rockylinux:8
    steps:
      - name: install repos with dependencies + prereqs
        run: |
          dnf -y install epel-release
          
      - name: enable powertools
        run: |
          dnf config-manager --set-enabled powertools
          
      - name: install Development Tools
        run: |
          dnf -y group install "Development Tools"
          
      - name: update everything
        run: |
          dnf -y update
          
      - name: install dependencies
        run: |
          dnf -y install hwloc-devel wget munge-devel openssl-devel rpm-build libevent-devel python3-devel
      
      - name: download tarball from upstream repository
        run: |
          wget ${UPSTREAM_PATH}
          
      - name: build rpms
        run: |
          rpmbuild --rebuild pmix-*.src.rpm
          
      

      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${secrets.GITHUB_TOKEN}
          files: /github/home/rpmbuild/RPMS/x86_64/pmix-*.x86_64.rpm 
          release: ${github.ref}
          message: message
          body: body
          prerelease: false
          draft: false
