on: [push]
jobs:
  first-job:
    name: produce rpms
    runs-on: ubuntu-22.04
    container: docker://rockylinux:8
    steps:
      - name: install repos with dependencies + prereqs
        run: |
          dnf -y install epel-release
          
      - name: enable powertools
        run: |
          dnf config-manager --set-enabled powertools
          
      - name: install Development Tools
        run: |
          dnf -y group install "Development Tools"
          
      - name: install dependencies
        run: |
          dnf -y install hwloc-devel wget munge-devel openssl-devel rpm-build libevent-devel python3-devel
      
      - name: download tarball from upstream repository
        run: |
          wget https://github.com/openpmix/openpmix/releases/download/v4.2.3/pmix-4.2.3-1.src.rpm
          
      - name: build rpms
        run: |
          rpmbuild --rebuild pmix-4.2.3-1.src.rpm
          
