on: [push]
jobs:
  first-job:
    name: produce rpms
    runs-on: ubuntu-22.04
    container: docker://rockylinux:8
    steps:
#      - name: download tarball from upstream repository
#        run: |
#          wget https://github.com/openpmix/openpmix/releases/download/v4.2.3/pmix-4.2.3-1.src.rpm
          
      - name: install dependencies
        run: |
          dnf -y install epel-release
